### ISSUE TITLE
missing description for binmode attribute

### ISSUE THREAD

**Issue by glasswalk3r** [perlancar/perl-File-Write-Rotate#12]
The Pod for the module is missing a description for the bindmode attribute.

There is a reader:

```
bindmode => STR
```
But that's all. I believe setting this to true would configure the log to binary mode, but I'm only guessing.

**Comment by perlancar** [comment]
Sorry, missed this PR/issue (didn't receive notification from GitHub).

Description now added. Basically the string will be passed as 2nd argument to `binmode()` so you can set PerlIO layers with it.

**Comment by perlancar** [comment]
Sorry, missed this PR/issue (didn't receive notification from GitHub).

Description now added. Basically the string will be passed as 2nd argument to `binmode()` so you can set PerlIO layers with it.
